# escape=`
FROM sixeyed/aspnet-3.5:windowsservercore-1809
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Install-WindowsFeature NET-HTTP-Activation; `
    Remove-Website -Name 'Default Web Site';`
    New-Website -Name 'petshop-web' -Port 80 -PhysicalPath 'C:\petshop-web\' -Force

COPY petshop-web.zip .
RUN Expand-Archive -Path petshop-web.zip -DestinationPath C:\